### ISSUE TITLE
Can I get the loudness per channel?

### ISSUE THREAD

**Issue by kaleidoscope-dev** [jiixyj/libebur128#104]
I'm currently processing wav file and I'm just adding samples read from the wav files with ebur128_add_frames_short(); and  ebur128_loudness_momentary(); 
But this will give me just one value calculated from the buffer. And the comment also said that the channels must be interleaved.

Can I get loudness levels per channel somehow?

**Comment by audionuma** [comment]
Hello,
there's no such thing as a _per channel_ loudness in the EBU R128 standard, unless you mean a mono single channel program.
What format (Stereo, 5.1, ...) are your input audio files ? What is your goal ?

**Comment by jiixyj** [comment]
Yes, right now you'd have to process each channel separately in a different `ebur128_state`. But as audionuma said, it very much depends on your use case.

For example, I don't think it is possible to recombine those different loudness values per channel into the "total" loudness value again, because there is some gating that is done *after* the summation of loudness values (see p. 21 of https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.1770-4-201510-I!!PDF-E.pdf).

**Comment by kaleidoscope-dev** [comment]
Thanks for the answers. I have a simple demo sine wave I got from samples here https://tech.ebu.ch/publications/ebu_loudness_test_set that I use for testing.  For example I use a 1kHz Sine -20 LUFS-16bit.

I already tried separating channels into separate states but I had some issues where each channel momentary value resulted in incorrect values ( some -17LUFS instead of -20). 

There's also the commend on using  ebur128_add_frames_short that says that "src array of source frames. Channels must be interleaved."  

But if it's possible to just process channels as separate  ebur128_state then I must have messed something up.  I'll try again.

**Comment by audionuma** [comment]
@kaleidoscope-dev : there seem to be a misunderstanding of the EBU R128 (aka BS 1770) loundess measurement (which is what this libebur128 library provides). It is not a per channel measurement but the measurement of the perceived loudness of a given multichannel audio program. It seems to me that what you are looking for is closer to a simple rms measurement on each channel, which is actually what a VU meter does with some ballistics / integration time tricks.

This being said, if you want to measure individual channels loudness with libebur128, you will need to instantiate one `ebur128_state` per channel and initialize it as a one channel instance. Then you can feed each of these instances with an array containing single channel audio data.

If your audio data reader delivers interleaved audio data, you will have to de-interleave the data.

**Comment by kaleidoscope-dev** [comment]
Thank you.
