### ISSUE TITLE
How to use this library to process PCM data

### ISSUE THREAD

**Issue by rsp4jack** [jiixyj/libebur128#115]
I have some PCM data (16bit, signed), stored in qint16 (aka short).
Now I want to analyze loudness using this library, how can I do?
I have tried to directly add them (`ebur128_add_frames_double(this->stat, &pcm, 1);`, in a `for` code block to enumerate data), it gets loudness "nan (not a number)"
and add them as dBFS, but it gets "nan" too.
and add them as amplitude (pcm data÷max pcm), it gets incorrect value.
So, how to add PCM data to ebur128_status?

**Comment by chirlu** [comment]
As the function name `ebur128_add_frames_double` indicates, it is for `double` values and not for `short`s.

**Comment by rsp4jack** [comment]
replaced with `ebur128_add_frames_short` but doesn't work.
Tested in -23dBFS, 1000hz sin wave, get -25.79LUFS.
In EBU Tech 3441, it must be -23LUFS.

**Comment by audionuma** [comment]
Hello,
have you tried to build and run the https://github.com/jiixyj/libebur128/blob/master/test/minimal-example.c ? Is it running as expected ?
Are you sure that `qint16` can directly be used as `int` without some sort of type casting ?

**Comment by rsp4jack** [comment]
qint16 is 16bit integer (aka short)

**Comment by rsp4jack** [comment]
I run minimal example and it works fine
