### ISSUE TITLE
Error linking speexdsp on Mac OS with MacPorts

### ISSUE THREAD

**Issue by audionuma** [jiixyj/libebur128#43]
Hello,
using commit 0bf8339ba08859531cdb5b8736a101302a51a2e7 on Mac OS 10.9.5, cmake and speexdsp installed with MacPorts.
```
$ which cmake
/opt/local/bin/cmake
$ cmake -version
cmake version 3.3.2
$ cd libebur128/build/
$ cmake ..
[snip]
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.28") 
-- checking for module 'speexdsp'
--   found speexdsp, version 1.2rc1
-- Status          found / disabled --
-- queue.h:        yes     using system copy of queue.h
-- speexdsp:       yes     no 
-- build static library and shared library!
-- not building tests, set ENABLE_TESTS to ON to enable
-- Configuring done
[/snip]
$ make
Scanning dependencies of target ebur128
[ 25%] Building C object ebur128/CMakeFiles/ebur128.dir/ebur128.c.o
[ 50%] Linking C shared library ../libebur128.dylib
ld: library not found for -lspeexdsp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libebur128.1.0.3.dylib] Error 1
make[1]: *** [ebur128/CMakeFiles/ebur128.dir/all] Error 2
make: *** [all] Error 2
```
After looking around `libebur128/ebur128/CMakeLists.txt`, I found where the issue comes from on my system : the `SPEEXDSP_LIBRARIES` variable used on line 65 is equal to `speexdsp` and does not include full path to the library.

I found a workaround after searching on sample cmake files around the web, although I cannot test possible regressions on other systems. Add two lines after line 51 :
```
      find_library(SPEEXDSP_LIBRARY speexdsp
             HINTS ${SPEEXDSP_LIBDIR} ${SPEEXDSP_LIBRARY_DIRS})
      set(SPEEXDSP_LIBRARIES ${SPEEXDSP_LIBRARY})

```
Is it worth a pull request ?

**Comment by jiixyj** [comment]
Thanks, I could reproduce this issue. I have just committed a possible fix that in principle works just like the code you posted. Could you try again, please?

**Comment by audionuma** [comment]
Well, that was a quick one !
Solved on my side.
Thanks.
