### ISSUE TITLE
Loudness range quartiles

### ISSUE THREAD

**Issue by sesse** [jiixyj/libebur128#44]
Hi,

Is it possible to get not only the LRA, but also the actual high and lows? (I see they are computed in ebur128_loudness_range_multiple(), but then immediately subtracted.) I assume calling ebur128_loudness_global() and adding/subtracting half of the LRA won't give the correct range?

The reason I'm asking is that I'd like to visualize the range, similar to what ebumeter does (middle row of http://kokkinizita.linuxaudio.org/linuxaudio/ebumeter-doc/ebumeter.png), and I can't find a way to extract this information currently.

Thanks!

**Comment by jiixyj** [comment]
It should not be too hard to add a new API for this use case. How does the LRA visualization of ebumeter work exactly? Is it controlled with the Start/Stop/Reset buttons?

**Comment by sesse** [comment]
FWIW, I solved my problem just by embedding ebumeter. It is >10x as fast for my use case anyway. Closing this as I don't need it anymore.
