### ISSUE TITLE
Relative Gating Threshold

### ISSUE THREAD

**Issue by kylophone** [jiixyj/libebur128#46]
It would be nice to expose the relative gating threshold value. I'm not sure, but I don't think there's any way to pull this value from ebur128_state_internal. Any idea? If not, I may add this and open a pull request. Thanks!

**Comment by kylophone** [comment]
See pull request. I'm finishing up work on dynamic loudness normalization filter for FFmpeg, and I'm using this libebur128. Hopefully you can merge this, relative threshold is an important value for dynamic loudness normalization. Let me know if anything needs to change. Thanks!

**Comment by uklauer** [comment]
The pull request is #47.

**Comment by kylophone** [comment]
This has been merged.
