### ISSUE TITLE
True Peak crash with 192kHz sample rate

### ISSUE THREAD

**Issue by dts350z** [jiixyj/libebur128#59]
With EBUR128_MODE_TRUE_PEAK | EBUR128_MODE_I (I want global LUFS and True Peak) version 1.20 is working with 44.1KHz and 96KHz, however at 192KHz I get a crash.

 Access violation writing location 0x00000000.

 Call stack is:

ebur128_realative_threshold()
ebur128_add_frames_float()

I will review the size of memory I am reserving with malloc but things were working with only EBUR128_MODE_I at all sample rates.

**Comment by dts350z** [comment]
176400 Hz sample rate is working. It only seems to be 192KHz that is broken.

FYI I compiled the test program and downloaded the test wav files to ensure all was working. I then added one test on an upsampled copy of seq-3341-23-24bit.wav.wav. It passed at sample rates below 192KHz and also crashed at 192kHz so I am confident the issue lies in the lib. vs. my useage of it.

**Comment by jiixyj** [comment]
Thanks for the report! This should be fixed in v1.2.2.
