### ISSUE TITLE
Intermittently strange result with very large true peak

### ISSUE THREAD

**Issue by jherby2k** [jiixyj/libebur128#72]
In my app's test suite I occasionally get a true peak like 2.1267647932558654E+38, which is obviously not correct (should be 1.014152). Doesn't happen with sample peaks, and like I said it is intermittent (about 1 time in 20).

I don't believe its a race condition or anything as this is an "album" with only 1 track, and my tests do not run in parallel.

I've seen it with 44.1 kHz, 48 kHz and 96 kHz versions of the same file.

**Comment by jiixyj** [comment]
Thanks for the report! I could reproduce it doing a complete true peak scan of my music library.
I think I fixed it in 2177c23cc74a8bdc8d088313b4d90f422d20d4aa. Doing another scan right now.

**Comment by jherby2k** [comment]
Thanks for your prompt reply! My tests are all passing now reliably. Do you think this warrants a 1.2.3 release?

Sent from Mail for Windows 10

**Comment by jiixyj** [comment]
Yeah, I think a 1.2.3 with this fixed would be appropriate.

**Comment by jiixyj** [comment]
Thank you for testing the fix!
