### ISSUE TITLE
How do i use this library to measure Loudness of Raw PCM Samples

### ISSUE THREAD

**Issue by ckarthickit** [jiixyj/libebur128#86]
Hi ,

I have a RAW PCM Sample (also know its Sample rate , and number of channels).
How do i use this library to measure loudness .
All the examples seem to use sound library that works with WAV,FLAC and other audio formats . Not with RAW files .

Kindly help

**Comment by ckarthickit** [comment]
My code looks like below (Note : There are lot of hardcoding as i am only testing)
I modified from the minimal-example code  : 
`
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

#include "ebur128.h"


int main(int ac, const char* av[]) {
  int channels = 2;
  int samplerate = 16000;
  size_t nr_frames_read;
  ebur128_state** sts = NULL;
  FILE* file;
  short* buffer;
  double loudness;
  int i;

  if (ac < 2) {
    fprintf(stderr, "usage: %s FILENAME...\n", av[0]);
    exit(1);
  }

  sts = malloc((size_t) (ac - 1) * sizeof(ebur128_state*));
  if (!sts) {
    fprintf(stderr, "malloc failed\n");
    return 1;
  }

  for (i = 0; i < ac - 1; ++i) {
    file = fopen(av[i + 1], "r");
    if (!file) {
      fprintf(stderr, "Could not open file with fopen!\n");
      return 1;
    }

    sts[i] = ebur128_init((unsigned) channels,
                          (unsigned) samplerate,
                          EBUR128_MODE_I);
    if (!sts[i]) {
      fprintf(stderr, "Could not create ebur128_state!\n");
      return 1;
    }

    /* example: set channel map (note: see ebur128.h for the default map) */
    if (channels == 5) {
      ebur128_set_channel(sts[i], 0, EBUR128_LEFT);
      ebur128_set_channel(sts[i], 1, EBUR128_RIGHT);
      ebur128_set_channel(sts[i], 2, EBUR128_CENTER);
      ebur128_set_channel(sts[i], 3, EBUR128_LEFT_SURROUND);
      ebur128_set_channel(sts[i], 4, EBUR128_RIGHT_SURROUND);
    }
    buffer = (short*) malloc(sts[i]->samplerate * sts[i]->channels * sizeof(short));
    if (!buffer) {
      fprintf(stderr, "malloc failed\n");
      return 1;
    }
    while (( nr_frames_read = fread(buffer, 1, sts[i]->samplerate, file) )) {
      ebur128_add_frames_short(sts[i], buffer, (size_t) nr_frames_read);
    }
    time_t begin = time (NULL);
    fprintf(stderr,"before_loud_calc %ld\n",begin);
    ebur128_loudness_global(sts[i], &loudness);
    time_t end = time (NULL);
    fprintf(stderr,"after_loud_calc %ld\n",end);
    fprintf(stderr,"Time for loudness_calc= %.2f\n",difftime(end, begin));
    fprintf(stderr, "%.2f LUFS, %s\n", loudness, av[i + 1]);


    free(buffer);
    buffer = NULL;

    if (fclose(file)) {
      fprintf(stderr, "Could not close input file!\n");
    }
  }
  time_t begin = time (NULL);
  ebur128_loudness_global_multiple(sts, (size_t) ac - 1, &loudness);
  time_t end = time (NULL);
  fprintf(stderr, "-----------\n%.2f LUFS\n", loudness);
  fprintf(stderr,"Time for loudness_calc= %.2f\n",difftime(end, begin));

  /* clean up */
  for (i = 0; i < ac - 1; ++i) {
    ebur128_destroy(&sts[i]);
  }
  free(sts);

  return 0;
}

`

**Comment by audionuma** [comment]
Hello,
you can (as an example) read RAW files using [libsndfile](http://www.mega-nerd.com/libsndfile/api.html#open).

This will require to manually set the `SF_FORMAT` field of the `SF_INFO` struct to `SF_FORMAT_RAW` _OR'ed_ with the appropriate subtypes (`SF_FORMAT_xx` and `SF_ENDIAN_xx`).

> When opening a file for read, the format field should be set to zero before calling sf_open(). The only exception to this is the case of RAW files where the caller has to set the samplerate, channels and format fields to valid values. All other fields of the structure are filled in by the library.

**Comment by ckarthickit** [comment]
Hi @audionuma  Yes i did saw that we can use libsndfile for that .
What i want to understand is can i just use RAW PCM samples directly ? 

I am planning to use this for Android platform and porting libsndfile is an overhead. 
I already have PCM samples at hand (From the player that i use)

**Comment by ckarthickit** [comment]
## I tried using WAV+SOUNDLIBRARY and got below output: 
-13.62 LUFS, /Users/karthikc/LOGS/d.wav
-----------
-13.62 LUFS

## I tried using the code mentioned above to read RAW PCM and got below output: 
-14.24 LUFS, /Users/karthikc/Documents/PROJECTS/VSTB/LOGS/pcm_46495183_2_16000_d_wav
-----------
-14.24 LUFS

Although they are close ,they are not exactly same .
I want to ensure that i am passing frames to the EBUR library correctly .

Thanks !

**Comment by jiixyj** [comment]
I believe you have to add your samples like this:
```
while (( nr_frames_read = fread(buffer, 1, sts[i]->samplerate * sts[i]->channels, file) )) {
  ebur128_add_frames_short(sts[i], buffer, (size_t) nr_frames_read / sts[i]->channels);
}
```
I.e. the third argument must be the number of frames, not the number of bytes read. I've modelled the API after the libsndfile frame read/write functions (http://www.mega-nerd.com/libsndfile/api.html#readf).

Does the loudness match if you do this?

Be aware that `fread` might return incomplete frames in the example above. Your code should probably handle this corner case.

**Comment by ckarthickit** [comment]
@jiixyj  

The output after the change looks off by a bigger margin .
./minimal-example d.wav 
-13.62 LUFS, d.wav
`-----------`
-13.62 LUFS
 
./pcm-test pcm_46495183_2_16000_d_wav 
-15.48 LUFS, pcm_46495183_2_16000_d_wav
`-----------`
-15.48 LUFS

**Comment by jiixyj** [comment]
Ah, the following should work (taking the size of one sample into accout):
```
    while ((nr_bytes_read = fread(buffer, 1, sts[i]->samplerate * sts[i]->channels * sizeof(uint16_t), file))) {
      ebur128_add_frames_short(sts[i], buffer, nr_bytes_read / sts[i]->channels / sizeof(uint16_t));
    }
```
...or, using the `size` argument of `fread`:
```
    while ((nr_frames_read = fread(buffer, sts[i]->channels * sizeof(uint16_t), sts[i]->samplerate, file))) {
      ebur128_add_frames_short(sts[i], buffer, nr_frames_read);
    }
```

**Comment by ckarthickit** [comment]
Awesome ! It works Thanks a lot for your prompt reply ! 

BTW , i have one more question , 

Does calling **ebur128_add_frames_short** takes a copy of the buffer into it's data structure every time and accumulates it until i call **ebur128_destroy** ? 
I haven't started looking into the code yet and hence wanted to clarify :)

**Comment by ckarthickit** [comment]
Also why specifically uint16_t.. Because it is 16-bit PCM ?

**Comment by jiixyj** [comment]
No, the buffer is not copied into the `ebur128_state`. What is accumulated though is a linked list of loudness values. This list may grow very large if you are scanning huge amounts of data. I suggest using `EBUR128_MODE_HISTOGRAM`, i.e. using `EBUR128_MODE_I | EBUR128_MODE_HISTOGRAM` as third argument to `ebur128_init`. This mode uses a more efficient data structure.

> Also why specifically uint16_t.. Because it is 16-bit PCM ?

Exactly.

**Comment by ckarthickit** [comment]
@jiixyj  Thanks a lot . I understand now . 
i will refactor my code to take the encoding into picture and read as mentioned above (16-bit pcm or 8-bit pcm respectively)

👍
