### ISSUE TITLE
Do we have a documentation that explains the internals of this library

### ISSUE THREAD

**Issue by ckarthickit** [jiixyj/libebur128#88]
Hi ,

Do we have a documentation (preferably a block diagram) that explains the internal data structures used in the library .

Also where can i find the EBUR 128 spec and what are the pre-requisites to understand the Specification

**Comment by audionuma** [comment]
Hello,
the specifications are based mainly on :

http://www.itu.int/rec/R-REC-BS.1770/en
https://tech.ebu.ch/docs/r/r128.pdf
https://tech.ebu.ch/docs/tech/tech3341.pdf
https://tech.ebu.ch/docs/tech/tech3342.pdf

**Comment by ckarthickit** [comment]
@audionuma  thanks for your response. 
Is there any blog available for understanding RAW Audio samples .What each sample's 16-bit (assuming it is a 16-bit PCM) value indicate and how does we come up with loudnes ?
