### ISSUE TITLE
ebur128_set_channel() returns a wrong error code

### ISSUE THREAD

**Issue by MarcinCiura** [jiixyj/libebur128#90]
According to the docs in [ebur128.h](https://github.com/jiixyj/libebur128/blob/master/ebur128/ebur128.h#L137), `ebur128_set_channel()` returns `EBUR128_SUCCESS` or `EBUR128_ERROR_INVALID_CHANNEL_INDEX`. Yet the function in [ebur128.c](https://github.com/jiixyj/libebur128/blob/master/ebur128/ebur128.c#L772) returns 0 (= `EBUR128_SUCCESS`) or 1 (= `EBUR128_ERROR_NOMEM`).

**Comment by jiixyj** [comment]
This is now fixed in master and matches the documentation. Theoretically, this could cause problems because it changes the ABI. If anyone is affected, please let me now. Normally, one shouldn't hit this if one checks for the number of channels beforehand.

**Comment by Moonbase59** [comment]
Ok with [loudgain](https://github.com/Moonbase59/loudgain).

**Comment by jiixyj** [comment]
This was included in the new 1.2.5 release.
