### ISSUE TITLE
Max. momentary erratic results with EBU test files(?)

### ISSUE THREAD

**Issue by nofishonfriday** [jiixyj/libebur128#93]
Hello,

first a bit of background:
I'm a contributor to the [SWS Extension](http://www.sws-extension.org/) ([Github repo](https://github.com/reaper-oss/sws)), an extension for the [REAPER](https://www.reaper.fm/) DAW. which implements offline Loudness scanning using libebur128.

I've scanned the files from the [EBU loudness test set](https://tech.ebu.ch/publications/ebu_loudness_test_set) with our Loudness scanner and they all pass, except for test set 13.
In [tech3341](https://tech.ebu.ch/docs/tech/tech3341.pdf) it specifies for these files:

> Max M = −23.0 ±0.1 LUFS, for each segment

However with our current implementation we get the following results:

![loudness for libur128](https://user-images.githubusercontent.com/7658194/46816335-0a2b0e00-cd7d-11e8-8d33-8df411a52b38.jpg)

I'm now trying to determine if there's a bug in our implementation (we use a modified version of libebur128) or if this may be an issue with the library itself.

Thank you.

**Comment by jiixyj** [comment]
Huh, this is weird. We have some tests for test set 13, and they run successfully: https://github.com/jiixyj/libebur128/blob/c13deee58f47427c9506f1b0b259c16f909edab9/test/tests.c#L367

Maybe this helps tracking down the problem.

**Comment by nofishonfriday** [comment]
Ah missed these tests, thanks for pointing me to it.
So the issue must be on our end, that's at least good to know.

Closing this, thanks again.
